version: '3.7'

services:

  web:
    build: ./src
    depends_on:
      - db
      - db-test
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src/:/usr/src/app/
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://avito_fastapi:avito_fastapi@db/avito_fastapi_dev
      - TEST_DATABASE_URL=postgresql://avito_fastapi:avito_fastapi@db-test/avito_fastapi_test
      - TZ=Europe/Moscow

  db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
      - POSTGRES_USER=avito_fastapi
      - POSTGRES_PASSWORD=avito_fastapi
      - POSTGRES_DB=avito_fastapi_dev
    ports:
      - 5432:5432

  db-test:
    image: postgres:12.1-alpine
    environment:
      - TZ=Europe/Moscow
      - PGTZ=Europe/Moscow
      - POSTGRES_USER=avito_fastapi
      - POSTGRES_PASSWORD=avito_fastapi
      - POSTGRES_DB=avito_fastapi_test
    ports:
      - 5433:5432

volumes:
  postgres_data: